<?php
// custom_timezone/custom_timezone.module

/**
 * Implements hook_page_attachments() to attach the JavaScript library.
 */
function custom_timezone_page_attachments(array &$attachments) {
  // Attach the JavaScript library to all pages.
  $attachments['#attached']['library'][] = 'custom_timezone/time-updates';
}

function custom_timezone_theme($existing, $type, $theme, $path){

  return [
    'my_custom_block' => [
       'variables' => [
			'formattedDayOfWeek' => NULL,
			'formatteddateTime' => NULL,
			'selectedTimezone' => NULL,
			'city' => NULL,
			'country' => NULL,	   
	   ],
    ],
  ];
}


